// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    booking_curve: {
        name: "booking_curve";
        parameters: {
          /** STRING - use sql.string() */
          ruta_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          dias_a_salida: number;
          /** @sqlType DOUBLE */
          load_factor: number;
        }>;
      };
    revenue_trend: {
        name: "revenue_trend";
        parameters: {
          /** INT - use sql.int() */
          dias: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          fecha: string;
          /** @sqlType DOUBLE */
          revenue_usd: number;
        }>;
      };
    route_ancillary_mix: {
        name: "route_ancillary_mix";
        parameters: {
          /** STRING - use sql.string() */
          ruta_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          tipo_ancillary: string;
          /** @sqlType DOUBLE */
          revenue_usd: number;
          /** @sqlType DOUBLE */
          attach_rate: number;
        }>;
      };
    route_demand_series: {
        name: "route_demand_series";
        parameters: {
          /** STRING - use sql.string() */
          ruta_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          fecha: string;
          /** @sqlType DOUBLE */
          indice_demanda: number;
          /** @sqlType BIGINT */
          reservas: number;
        }>;
      };
    route_explorer: {
        name: "route_explorer";
        parameters: {
          /** STRING - use sql.string() */
          sort_key: SQLStringMarker;
          /** STRING - use sql.string() */
          sort_dir: SQLStringMarker;
          /** INT - use sql.int() */
          limit: SQLNumberMarker;
          /** INT - use sql.int() */
          offset: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          ruta_id: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType DOUBLE */
          ocupacion: number;
          /** @sqlType DOUBLE */
          revenue_usd: number;
          /** @sqlType DOUBLE */
          tarifa_propia: number;
          /** @sqlType DOUBLE */
          comp_mediana: number;
          /** @sqlType DOUBLE */
          brecha_pct: number;
          /** @sqlType DOUBLE */
          indice_demanda: number;
          /** @sqlType STRING */
          accion: string;
          /** @sqlType BIGINT */
          total_rutas: number;
        }>;
      };
  }
}
